_BASE_: "DECOLA_PHASE1_O365_CLIP_SwinL_4x.yaml"
MODEL:
  WEIGHTS: "output_local/standard/multi-node/standard-DECOLA/phase1_swinl_ddetr_bs32_4x/ppk_300_encl_ppk_10000_look_forward_twice_True/output/model_final.pth"
  DECOLA:
    WEAK_LOSS_PSEUDO_TYPE: 'max-score'
    USE_PSEUDO_LABELING_FOR_WEAK_LOSS: True 
    PROB_A_OBJECT: 1.0
    ORACLE_EVALUATION: False 
    TEST_CLASS_CONDITIONED: False 
    ZS_WEIGHT_PATH: 'datasets/metadata/lvis-21k+o365+oid_clip_a+cname.npy'
    NO_FED_LOSS_LIST: [True, True, True]
    ONLINE_LABELING: True 
  DETR:
    NUM_OBJECT_QUERIES: 300
    NUM_CLASSES: 21311 # in21 + o365 + oid
INPUT:
  CUSTOM_AUG: ResizeShortestEdge
  MIN_SIZE_TRAIN_SAMPLING: range
  MIN_SIZE_TRAIN: [480, 800]
DATASETS:
  TRAIN: ("imagenet_21k_oid_v7_train","imagenet_21k_objects365_v2_train","imagenet_lvis-21k")
  TEST: ("lvis_v1_val",)
SOLVER:
  STEPS: (583462,)
  MAX_ITER: 648291 # = 1728775 (images) * 12 (epochs) / 32 (batch-size)
  IMS_PER_BATCH: 16
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 1, 4]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [1, 2, 4]
  USE_RFS: [False, False, False]
  DATASET_MIN_SIZES: [[480, 800], [480, 800], [240, 400]]
  DATASET_MAX_SIZES: [1333, 1333, 667]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'box', 'image']
  NUM_WORKERS: 8
  USE_TAR_DATASET: True
WITH_IMAGE_LABELS: True 