_BASE_: "DECOLA_PHASE1_O365_CLIP_SwinT.yaml"
MODEL:
  WEIGHTS: "weights/DECOLA_PHASE1_O365_CLIP_SwinT.pth"
  DECOLA: 
    WEAK_LOSS_PSEUDO_TYPE: 'max-score'
    USE_PSEUDO_LABELING_FOR_WEAK_LOSS: True 
    PROB_A_OBJECT: 1.0
    ORACLE_EVALUATION: False 
    TEST_CLASS_CONDITIONED: False 
    ZS_WEIGHT_PATH: 'datasets/metadata/lvis-21k+o365_clip_a+cname.npy'
    TEST_SCORE_THRESHOLD: 0.0
  DETR:
    NUM_OBJECT_QUERIES: 300
    NUM_CLASSES: 20710 # in21 + o365 
INPUT:
  CUSTOM_AUG: ResizeShortestEdge
  MIN_SIZE_TRAIN_SAMPLING: range
  MIN_SIZE_TRAIN: [480, 800]
DATASETS:
  TRAIN: ("imagenet_21k_objects365_v1_train","imagenet_lvis-21k")
  TEST: ("lvis_v1_val",)
SOLVER:
  STEPS: (449853,)
  MAX_ITER: 511197
  IMS_PER_BATCH: 32
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 8]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [1, 4]
  USE_RFS: [False, False]
  DATASET_MIN_SIZES: [[480, 800], [240, 400]]
  DATASET_MAX_SIZES: [1333, 667]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'image']
  NUM_WORKERS: 8
  USE_TAR_DATASET: True
WITH_IMAGE_LABELS: True 
TEST:
  DETECTIONS_PER_IMAGE: 9999
