from detectron2.config import CfgNode as CN

def add_decola_config(cfg):
    _C = cfg
    _C.MODEL.DECOLA = CN() 
    _C.MODEL.DECOLA.USE_PROMPT_EMBED_BIAS = False 
    _C.MODEL.DECOLA.PER_PROMPT_TOPK = 300 
    _C.MODEL.DECOLA.FIRST_STAGE_ENC_LOSS_PER_PROMPT_TOPK = 10000
    _C.MODEL.DECOLA.USE_PIXEL_FEATURE_AS_QUERY = False 
    _C.MODEL.DECOLA.USE_PROMPT_EMBED_AS_QUERY = False 
    _C.MODEL.DECOLA.FED_FREQ_WEIGHT = 0.5  
    _C.MODEL.DECOLA.ZS_WEIGHT_DIM = 512 
    _C.MODEL.DECOLA.ZS_WEIGHT_PATH = "datasets/metadata/lvis_v1_clip_a+cname.npy" 
    _C.MODEL.DECOLA.ZS_OBJECT_WEIGHT_PATH = "datasets/metadata/lvis_v1_clip_a+object.npy" 
    _C.MODEL.DECOLA.ORACLE_EVALUATION = False 

    _C.MODEL.DECOLA.PROB_A_OBJECT = 1.0
    _C.MODEL.DECOLA.TEST_CLASS_CONDITIONED = False 
    
    _C.MODEL.DECOLA.FIRST_STAGE_EMBED_NORM = True 
    _C.MODEL.DECOLA.SECOND_STAGE_EMBED_NORM = True 

    _C.MODEL.DECOLA.MULTI_CLASS_SECOND_STAGE = False 
    _C.MODEL.DECOLA.TEST_SCORE_THRESHOLD = 0.0
    _C.MODEL.DECOLA.WITH_IMAGE_LABELS = False 
    
    _C.MODEL.DECOLA.WEAK_LOSS_PSEUDO_TYPE = 'max-score'
    _C.MODEL.DECOLA.USE_PSEUDO_LABELING_FOR_WEAK_LOSS = False 
    _C.MODEL.DECOLA.APPLY_LOSS_ONLY_WITHIN_IMAGE = False 
    _C.MODEL.DECOLA.NO_BOX_LOSS_FOR_PSEUDO_LABELS = False 
    _C.MODEL.DECOLA.PSEUDO_LOSS_MIN_SIZE_LIMIT = 0.0 

    _C.MODEL.DECOLA.USE_ENCODER_CHECKPOINT = False 
    _C.MODEL.DECOLA.USE_DECODER_CHECKPOINT = False 
    _C.MODEL.DECOLA.OFFLINE_PSEUDO_LABELER_PATH = ""
    _C.MODEL.DECOLA.ZS_WEIGHT_PATH_LIST = []

